### ISSUE TITLE
No sign of storm track in runs with `OFCL` (faked as `BEST`) track

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [oceanmodeling/ondemand-storm-workflow#22]
Here are the comparison of SCHISM outputs (`out_2d_1.nc`) for `BEST` and fake `OFCL` tracks of hurricane florence!
Looks like the `OFCL` track run does not have storm track. 

![image](https://github.com/oceanmodeling/ondemand-storm-workflow/assets/132295102/89c38213-c8f0-41dc-a3be-37e540a408aa)

![image](https://github.com/oceanmodeling/ondemand-storm-workflow/assets/132295102/742c72e8-5bf3-4a41-b9a7-e55f3e4e32da)

![image](https://github.com/oceanmodeling/ondemand-storm-workflow/assets/132295102/89fe90dc-7339-47a4-b752-dc5986c17a20)

**Comment by FariborzDaneshvar-NOAA** [comment]
**Update on the PaHM models with faked `BEST` track run!**
@pvelissariou1 and @SorooshMani-NOAA, Here are outputs of SCHISM run with faked `BEST` track and two `model_type_pahm` values (1: Holland, and 10: GAHM)

![image](https://github.com/oceanmodeling/ondemand-storm-workflow/assets/132295102/9d92b19f-fcfc-40c8-baff-58be4072460f)

As you see, both did not simulate wind (zero wind speed for the entire domain)!

**Comment by pvelissariou1** [comment]
@Fariborz Daneshvar - NOAA Affiliate ***@***.***> Fariborz
did you by any chance run your track file through PaHM standalone? If yes,
did you plot
the results from PaHM? When I used your track file in PaHM I actually saw
wind speeds that are not zero (> 1.0 m/s). Keep in mind that,
if the hurricane (eye) is not in the domain or near the domain the wind
fields (speed) will be zero. I don't know what time frame you plotted and
you have zero winds (maybe the storm has not reached the domain yet) but
see if you have this issue at later times when the storm has approached the
domain.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1 I think there might be some different between the two code. You ran the track through PaHM standalone a couple of days ago and it worked, but using SCHISM it doesn't seem to work. We're using SCHISM commit `ddf1564`

**Comment by pvelissariou1** [comment]
If I remember correctly, the PaHM core code in SCHISM is exactly the same
as in PaHM standalone. I have checked that a couple of times.
Later today I will check again and also the commits. I have run
PaHM+ADCIRC, PaHM+ADCIRC+WW3 in CoastalApp-testsuite without noticing any
issues.
Let me check though and I'll let you guys know about my findings.


Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by SorooshMani-NOAA** [comment]
I understand, that's why it's strange. Also please let us know if it helps if we debug it. In that case what are the flags we need to set to get the debug symbols, and how would we have to start SCHISM to debug?

**Comment by FariborzDaneshvar-NOAA** [comment]
@pvelissariou1 Yes, I ran PaHM standalone for the faked `BEST` track (see plots for max wind speeds here: https://github.com/noaa-ocs-modeling/PaHM/issues/27#issuecomment-1669875713)

As @SorooshMani-NOAA mentioned, it might be a difference in two codes?!

**Comment by FariborzDaneshvar-NOAA** [comment]
This issue is been addressed here: https://github.com/noaa-ocs-modeling/PaHM/issues/29
