### ISSUE TITLE
latitude-dependent Coriolis

### ISSUE THREAD

**Issue by yichengt900** [oceanmodeling/ondemand-storm-workflow#28]
@SorooshMani-NOAA I noticed in the current workflow that `ncor=0` (constant Coriolis parameter) is used for the schism model configuration. Although I think it is not a big deal for most storm events, we might consider switching to `ncor=1`  (the latitude-dependent Coriolis) to fully gain the benefits of using large-scale surge simulation.
FYI @FariborzDaneshvar-NOAA

**Comment by FariborzDaneshvar-NOAA** [comment]
See here for the impact of `ncor`: https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/issues/109#issuecomment-1715988737

**Comment by SorooshMani-NOAA** [comment]
I need to update the `pyschism` version and also add `ncor=1` to the config of the workflow.

**Comment by SorooshMani-NOAA** [comment]
I believe this has been already addressed. @FariborzDaneshvar-NOAA please let me know if you have noticed any issues with it, thanks!

**Comment by FariborzDaneshvar-NOAA** [comment]
@SorooshMani-NOAA All good, thanks!
