### ISSUE TITLE
Add option for symmetric vs GAHM to singularity workflow

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/ondemand-storm-workflow#36]
The option can be specified in `coupledmodeldriver` as an `attribute` `model` in `BestTrackForcingJSON`:

```python
BestTrackForcingJSON(
    nhc_code=f'{args.name}{args.year}',
    interval_seconds=3600,
    nws=20,
    fort22_filename=workdir/'track_files'/'original.22',
    attributes={'model': 'gahm'}
)
```

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA if this works fine please let me know so that I can mark this as done. Thanks!

**Comment by FariborzDaneshvar-NOAA** [comment]
It worked with the `symmetric` option, now testing it with `gahm` too

**Comment by FariborzDaneshvar-NOAA** [comment]
> @FariborzDaneshvar-NOAA if this works fine please let me know so that I can mark this as done. Thanks!

@SorooshMani-NOAA Thanks for adding this feature. I tested the workflow with both `pahm_mode` options of `gahm` and `symmetric`. All good, you can close this ticket.
