### ISSUE TITLE
Upgrade to Prefect 2.x

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/ondemand-storm-workflow#5]
Prefect cloud stops supporting Prefect v1 and the accounts will Freeze on May 1st.

**Comment by SorooshMani-NOAA** [comment]
@saeed-moghimi-noaa 

Given the number of tasks and flows we have and how convoluted they are written, migrating from version 1 to 2 might not be as straightforward as I hoped it to be. 

The amount of work looks to be similar to a rewrite in a new workflow manager. That makes me wonder, if we really want to stick with Prefect and whether the effort is worth it, or do we want to just use a different, e.g. cloud native (AWS Step Function, or Azure Logic Apps), workflow manager(s)?

**Comment by saeed-moghimi-noaa** [comment]
Hi @SorooshMani-NOAA 

Very good question! Lets have a meeting to discuss our options then to present them to our partners.

Thanks,
-Saeed

**Comment by saeed-moghimi-noaa** [comment]
Hi @SorooshMani-NOAA 

I asked this question at the EPIC meeting. 

`Is there any suggested workflow management software by EPIC (e.g. ECflow)? We are developing an "on-demand cloud based hurricane surge system" with distributed resouces on native AWS as well as managed resources at NOAA-RDHPCS cloud. To satisfy these requirments and have a native Python interface we utilized PREFECT (https://www.prefect.io/opensource/). We want to see if you have specific suggestion for us. Thanks. Saeed.Moghimi@noaa.gov`

They will reach out to us for a meeting. We most likely need to meet with:
- Christina Holt - NOAA Affiliate
- Keven Blackman - NOAA Affiliate
- Fredrick Gabelmann - NOAA Affiliate <fredrick.gabelmann@noaa.gov>

-Saeed

**Comment by SorooshMani-NOAA** [comment]
I'm still reading about ECFlow, but my first impression is that it's a system that binds a bunch of shell-scripts with the ability to add triggers and dependencies on when or on what condition to execute each. Each script is executed as task and can trigger more ECFlow commands (i.e. child commands) to control the overall job flow. 

ECFlow is client-server based, a server needs to be started and all the clients talk to that. However it still looks to be different from the server-worker architecture used in Prefect.

There is both a Python API and a CLI based API for defining the workflow, tasks, dependencies, triggers, and schedules. However it seems that the workflow itself cannot be branched conditionally (unless through managing triggers and completes, etc.). 

Our workflow needs branching based on some of the workflow parameters (unless we implement things differently), e.g. whether to run on PW or AWS, or to use ParametricWind or not, or to couple wind and wave or not, etc.. I'm not sure if it's easy to add all that logic into ECFlow. Maybe for each "branch" a new "family" of tasks with different dependencies need to be created, since the Python API that **defines** the workflow can still have conditions on how to define the tasks (and their dependecy, etc.). Then we'll have multiple families that we can choose from depending on the conditions of how to run things for our workflow.

**Comment by SorooshMani-NOAA** [comment]
Using `events` in ECFlow and `family` logical units can help in creating a hierarchy similar to what we have with Prefect. However the part about remote host code execution still seems lacking. What if SSH connection drops, does the task or family of tasks fail?

**Comment by SorooshMani-NOAA** [comment]
Using ECFlow, for long jobs one can create waiter tasks that ping the remote resource multiple times and check the status and send either complete or failed event to trigger the next actions.

**Comment by SorooshMani-NOAA** [comment]
It seems that ECFlow has the ability to run pure Python task scripts as well: https://ecflow.readthedocs.io/en/latest/ug/user_manual/the_ecflow_pre-processor/locating_ecf_file.html

I'm beginning to like ECFlow, although there are some things that might be harder on ECFlow due to its architecture vs Prefect.

**Comment by SorooshMani-NOAA** [comment]
I'm still not sure how each run of the workflow suite is separated from the next. For example how can we run the hindcast for two storms at the same time?

**Comment by SorooshMani-NOAA** [comment]
Multiple ECFlow servers can be started on different infrastructure, and the client can be called remotely. This way we emulate the server/agent relationship we currently have in Prefect. (?) https://ecflow.readthedocs.io/en/latest/ug/user_manual/ecflow_server/starting_the_ecflow_server.html

**Comment by SorooshMani-NOAA** [comment]
As a side note, looking at UFS repos, it seems that they originally intended to use ECFlow (as described in Andre's presentation), but then ended up using Rocoto instead.

**Comment by SorooshMani-NOAA** [comment]
After trying out the ECFlow tutorial, it looks to me that the workflow is mostly meant for on schedule runs, not on-demand type of runs. I'll update this comment as I gather more information...

**Comment by SorooshMani-NOAA** [comment]
Using ECFlow on a remote machine (https://ecflow.readthedocs.io/en/latest/tutorial/advanced_topics/running-the-jobs.html) seems to require shared file location/system (?)
> Let us run the tasks on a remote machine. For that we could use the unix command rsh. We would like the name of the host to be defined by an [variable](https://ecflow.readthedocs.io/en/latest/glossary.html#term-variable) called HOST. We assume that all the files are visible on all the hosts, i.e. using NFS.

If that's a hard requirement, then it doesn't make sense to use ECFlow for our multiplatform workflow (AWS + PW + ...)

**Comment by SorooshMani-NOAA** [comment]
Useful information about native python scripts in ECFlow: https://ecflow.readthedocs.io/en/latest/ug/cookbook/native_python_task.html

**Comment by SorooshMani-NOAA** [comment]
For some reason the Prefect agent on the EC2 keeps crashing after a "_Service exceeded error threshold._" error

**Comment by SorooshMani-NOAA** [comment]
After the fix to #14 suggested on the forum, as well as removing the flow stuck in "cancelling" state, agents have been alive for at least 1 day, the PW run (3 member) is in solve state and is going through.

**Comment by SorooshMani-NOAA** [comment]
For now we abandoned Prefect workflow dev.
