### ISSUE TITLE
Enable rmax persistent vs per isotach perturbation

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/ondemand-storm-workflow#60]
The latest `ensembleperturbation` PR (https://github.com/noaa-ocs-modeling/EnsemblePerturbation/pull/154) will be merged soon, update the dependency spec to use the latest code and update the scripts to add the option for using persistent vs per isotach perturbation that is implemented by @WPringle

**Comment by SorooshMani-NOAA** [comment]
@WPringle a quick question. I am a little confused about what combinations are right. This is my understanding of the different combinations we want to try (question parts bold-italicized):

| Rmax filling | Perturbation | Vortex Model |
| - | - | - |
| Persistent RMax (like before but just with hotstart, speed & quadrant fix) | Old perturbation (persistent) | Holland | 
| Based on NHC paper | **_Old perturbation (persistent)_** | Holland |
| **_Not filling Rmax_** | New perturbation (GAHM param based) | GAHM |

The confusion comes from the fact that GAHM doesn't use RMax, but Holland does, so why does it matter to have RMax fcst if we're using GAHM? Or to use GAHM based perturbation if we're using Holland?

**Comment by WPringle** [comment]
@SorooshMani-NOAA For the second row when we fill Rmax using regression based on NHC paper we should use the new perturbation.

**Comment by WPringle** [comment]
@SorooshMani-NOAA 
Rmax regression forecast: Use `radius_of_maximum_wind` variable
Rmax persistent forecast: Use `radius_of_maximum_wind_persistent` variable

**Comment by WPringle** [comment]
As for Holland or GAHM we can use either of them interchangeably. If the isotachs are perturbed then you can still use Holland it just won't have any effect. 
The additional test we may want to do is if we do not do any isotach perturbation and run with GAHM and compare to GAHM with isotach perturbation.

**Comment by WPringle** [comment]
So it's really as simple as:
Rmax regression:       Holland vs GAHM isotach perturb vs GAHM no isotach perturbation
Rmax pesistent:         Holland vs GAHM isotach perturb vs GAHM no isotach perturbation

**Comment by WPringle** [comment]
Although I should not doing Rmax persistent with GAHM with isotach peturb should not work well because the Rmax will not be very consistent with the isotachs

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA are we currently doing Holland or GAHM? Because right now we still don't have isotach perturb available in the workflow version you have. I'm working on it in this ticket, it'll be ready soon since the actual implementation is done and merged by @WPringle in `ensembleperturbation`

**Comment by WPringle** [comment]
@SorooshMani-NOAA I believe that the current version with GAHM did have isotach perturbation but only perturbing each isotach by the same distance [n mi] as the Rmax perturbation. So it does something..

**Comment by SorooshMani-NOAA** [comment]
Yes, but this would add some uncertainty that we don't account for, right? That's what I mean, that it might not give us improved results with GAHM.

**Comment by WPringle** [comment]
@SorooshMani-NOAA Sure it might not which is what we do want to look at yes

**Comment by SorooshMani-NOAA** [comment]
OK, we need to use ondemand workflow [v0.1.2](https://github.com/oceanmodeling/ondemand-storm-workflow/releases/tag/v0.1.2) and higher with GAHM given the discussion with @WPringle. Make sure to use isotach based perturbation and **not** persistent (in the input file) for new runs with GAHM. For Holland we need to use persistent, but we also need to use the older stormevents (1.2.10) for Holland. Probably we need to hash this out in the ensemble meeting (if we can make it next week given HPC training!)

**Comment by WPringle** [comment]
You can use the isotach perturbation with Holland too, not only persistent. In fact, we can try just compare RMW forecast vs persistent using only Holland model to test.

**Comment by SorooshMani-NOAA** [comment]
@WPringle I think I'm still a bit confused on the combinations ... let's have a discussion sometime soon

**Comment by WPringle** [comment]
Sure I just sent invite if u r free at 2 pm CT

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
